version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.ssh:/opt/hokei/.ssh
      - ~/.ssh/id_rsa:/opt/hokei/.ssh/id_rsa
      - ..:/opt/hokei/code
      - ../.devcontainer/.zshrc:/opt/hokei/.zshrc
    command: ["tail -f /dev/null"]

volumes:
  esdata: